### ISSUE TITLE
hubot-command-blacklist is not in npm

### ISSUE THREAD

**Issue by waynehoover** [kristenmills/hubot-command-blacklist#1]
`npm install hubot-command-blacklist --save` doesn't work.

`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hubot-command-blacklist`

**Comment by kristenmills** [comment]
Yep. I'll publish it when I get a chance. (Within 24 hrs probably) For now you can npm install the github repo and that should work.

**Comment by kristenmills** [comment]
Closing because it is now published
