### ISSUE TITLE
Listener middleware fires for all Messages, not just TextMessages

### ISSUE THREAD

**Issue by technicalpickles** [kristenmills/hubot-command-blacklist#2]
Keep in mind that listener middleware fires for every listener type, not just ones from `robot.hear` and `robot.respond`. `robot.

Those aren't "commands" per se, so you probably only want to reply on text messages. You can check for the presence of `context.response.message.text` or if `context.response.message instanceof TextMessage`.

**Comment by kristenmills** [comment]
Ah yeah. I'll change that.
